compressionLevel: mixed

defaultSemverRangePrefix: ''

nodeLinker: node-modules

tsEnableAutoTypes: true

npmRegistryServer: 'https://registry.npmjs.org'

yarnPath: .yarn/releases/yarn-4.1.1.cjs

npmPublishRegistry: https://registry.npmjs.org/
