name: Manual Release

on:
  workflow_dispatch:

env:
  HUSKY: 0

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Release
        run: pnpm exec semantic-release --ci --debug
        env:
          GIT_AUTHOR_NAME: haqq-ci
          GIT_AUTHOR_EMAIL: haqq-ci@haqq.network
          GIT_COMMITTER_NAME: haqq-ci
          GIT_COMMITTER_EMAIL: haqq-ci@haqq.network
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
